DEBUG = True
JSON_AS_ASCII = False

HOSTNAME = '192.168.60.129'
PORT = '4306'
DATABASE = 'test'
USERNAME = 'root'
PASSWORD = '123456'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI

#设置是否跟踪每次的修改
SQLALCHEMY_TRCK_MODIFICATIONS = True
SECRET_KEY = "FHREHTRYHGGHTFhtrhhRThggREGsHERhREhr"
